stages:
  - build
  - deploy

variables:
  SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  LATEST_IMAGE: $CI_REGISTRY_IMAGE:latest
  CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $DOCKER_IMAGE
    - docker push $LATEST_IMAGE
